apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-alb-sample
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/lean-saas-tech.git  # Replace with your actual repository URL
    targetRevision: HEAD
    path: sample/sample-nginx-alb
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true